# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2bb01b6249fb8ec57e08d760d5fa5c0d10bfce3e94bf62e2f802e18822f5d3ec1b77e73427e7162e01507e27871d084b4309acf0c4c156d9d14936a1c561d66a

test:
  secret_key_base: 9457dd99a41a96eb75f275f0bd9b7a51e7a3a7ae13eb560832eb5a0148e8448b948f6288734f0db411a90ca96698d39c5a21af882a98fa43aacc32a81a1bdf92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
